backend:
  name: github
  repo: bradybrenot/recipes-brenot-ca # Path to your GitHub repository
  branch: master

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "recipes" # Used in routes, e.g., /admin/collections/blog
    label: "Recipes" # Used in the UI
    folder: "content/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

      - {label: "Source", name: "source", widget: "string", required: false, default: ""}
      - {label: "Categories (comma-separated)", name: "categories", widget: "list", required: false, default: "", hint: "comma-separated, e.g. \"spicy, slow cooker, beans\""}
      - {label: "Cook Time (minutes)", name: "cookTime", widget: "number", required: false, default: ""}
      - {label: "Prep Time (minutes)", name: "prepTime", widget: "number", required: false, default: ""}
      - {label: "Preheat (℉)", name: "preheat", widget: "number", required: false, default: ""}

      - { label: "Description", name: "body", widget: "markdown", required: false, hint: "on the actual website, this shows up before the rest of the recipe. Use it for food blogging, videos, a description, whatever"}
      - { label: "Author", name: "author", widget: "string", required: false, default: "", hint: "if left blank, this will be filled in automatically" }
      - { label: "LastEdited", name: "lastEdited", widget: "hidden", required: false, default: "" }

      - label: "Ingredient Sets"
        name: "ingredientsets"
        widget: "list"
        required: false
        default: []
        fields:
          - {label: "Name", name: "name", minimal : true, widget: "string", default: "Ingredients", required: false}
          - label: "Ingredients"
            name: "ingredients"
            widget: "list"
            sortable_fields: ['amount', 'description']
            summary: "{{amount}} - {{description}}"
            collapsed: false
            minimize_collapsed: true
            fields:
            - {label: "Amount", name: "amount", minimal : true, widget: "string", required: false, default: ""}
            - {label: "Description", name: "description", minimal : true, widget: "string", required: false, default: ""}
      - label: "Direction Sets"
        name: "directionsets"
        widget: "list"
        required: false
        default: []
        fields:
          - {label: "Name", name: "name", minimal : true, widget: "string", default: "Directions", required: false}
          - label: "Steps"
            name: "steps"
            widget: "list"
            summary: "{{body}}"
            collapsed: false
            minimize_collapsed: true
            field: {label: "body", name: "body", minimal: true, widget: "markdown", required: false}
      - label: "Notes"
        name: "notes"
        widget: "list"
        summary: "{{body}}"
        collapsed: false
        minimize_collapsed: true
        field: {label: "body", name: "body", minimal: true, widget: "markdown"}
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: "string", required: false, default: "" }
      - { label: "LastEdited", name: "lastEdited", widget: "hidden", required: false, default: "" }